//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace personelYonetimi
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMPLOYEES
    {
        public int employee_id { get; set; }
        public int age { get; set; }
        public string first_name { get; set; }
        public string last_name { get; set; }
        public string gender { get; set; }
        public int team_id { get; set; }
        public int salary { get; set; }
    
        public virtual TEAMS TEAMS { get; set; }
    }
}
